name: meta_race
description: "A meta race car driving simulator application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1

  # Booking and Time Logic (Main Moto)
  intl: ^0.19.0
  table_calendar: ^3.1.2

  # Local Database
  sqflite: ^2.3.0
  path: ^1.9.0

  # Real-time Messaging (MQTT)
  mqtt_client: ^10.0.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/meta-race.jpg